# Generic language, so that the container/VM is lightweight.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack

install:
  - make git-version
  - stack setup --no-terminal
  - stack build --no-terminal --only-snapshot

script:
  - stack --no-terminal test
