site_name: Corydalis
docs_dir: docs
theme: readthedocs
site_author: Iustin Pop
site_url: https://corydalis.readthedocs.io/
nav:
- Home: index.md
- Installation guide: install.md
- Manual: manual.md
- Development notes: devel.md
- TODOs: todo.md
- Changelog: changelog.md
