name:    corydalis
version: "0.2.0"
license: AGPL-3
license-file: [LICENCE, LICENCE-AGPL]
category: Image
author:
  - Iustin Pop <iustin@k1024.org>
maintainer:
  - Iustin Pop <iustin@k1024.org>
copyright:
  - (c) 2013 Iustin Pop
github: iustin/corydalis
stability: experimental
synopsis: A photo library management and viewer
description: >
  Corydalis is a simple application to help manage offline (as in
  non-cloud) collections of RAW and processed pictures. It doesn't
  replace your RAW processor but instead acts as a companion to it,
  giving a parallel view on all your files.

  It is also an image viewer, designed to work across and understand
  your entire photo collection; the desktop-only viewers (e.g. Geeqie)
  are folder-based, not collection-based. This aspect aims to offer a
  similar experience of viewing your photos as it would be if you
  stored them in the cloud (but many features are still missing).

  See README.md for more details.

extra-source-files:
  - templates/*
  - static/css/*
  - static/fonts/*
  - static/js/*
  - README.md
  - docs/*.md
  - stack.yaml
  - package.yaml
  - mkdocs.yml
  - config/favicon.ico
  - config/models
  - config/robots.txt
  - config/routes
  - config/settings.yml.sample
  - config/test-settings.yml
  - app/devel.hs
  - .ghci
  - .dir-locals.el
  - Makefile
  - git-version

dependencies:
  # Due to a bug in GHC 8.0.1, we block its usage
  # See: https://ghc.haskell.org/trac/ghc/ticket/12130
  - base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

  # version 1.0 had a bug in reexporting Handler, causing trouble
  - classy-prelude-yesod >=0.10.2 && <1.0 || >=1.1
  - aeson >=0.6 && <1.3
  - async
  - blaze-markup
  - blaze-svg
  - bytestring >=0.9 && <0.11
  - case-insensitive
  - classy-prelude >=0.10.2
  - classy-prelude-conduit >=0.10.2
  - clock
  - conduit >=1.0 && <2.0
  - containers
  - data-default
  - deepseq
  - directory >=1.1 && <1.4
  - fast-logger >=2.2 && <2.5
  - file-embed
  - filepath >=1.3
  - foreign-store
  - hjsmin >=0.1 && <0.3
  - http-conduit >=2.1 && <2.3
  - monad-control >=0.3 && <1.1
  - monad-logger >=0.3 && <0.4
  - old-locale
  - optparse-applicative
  - persistent >=2.0 && <2.8
  - persistent-sqlite >=2.1.1 && <2.8
  - persistent-template >=2.0 && <2.8
  - prefix-units >=0.2 && <0.3
  - random
  - regex-tdfa
  - safe
  - scientific
  - shakespeare >=2.0 && <2.1
  - store
  - template-haskell
  - temporary
  - text >=0.11 && <2.0
  - time
  - transformers
  - typed-process
  - unix >=2.6
  - unordered-containers
  - vector
  - wai
  - wai-extra >=3.0 && <3.1
  - wai-logger >=2.2 && <2.4
  - warp >=3.0 && <3.3
  - warp-tls >=3.2 && <3.3
  - yaml >=0.8 && <0.9
  - yesod >=1.4.3 && <1.5
  - yesod-auth >=1.4.0 && <1.5
  - yesod-auth-hashdb >=1.6.0 && <1.7
  - yesod-core >=1.4.30 && <1.5
  - yesod-form >=1.4.0 && <1.5
  - yesod-static >=1.4.0.3 && <1.6

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs:
    - src
    - app
  exposed-modules:
    - Application
    - Cache
    - Exif
    - Foundation
    - Handler.Browse
    - Handler.Common
    - Handler.Curate
    - Handler.Folder
    - Handler.Home
    - Handler.Image
    - Handler.LensInfo
    - Handler.LensStats
    - Handler.Reload
    - Handler.Search
    - Handler.Settings
    - Handler.Untracked
    - Handler.Utils
    - Handler.View
    - Handler.Widgets
    - Import
    - Import.NoFoundation
    - Indexer
    - Model
    - Pics
    - Settings
    - Settings.Development
    - Settings.StaticFiles
    - Types
  other-modules:
    - Compat.Orphans

  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  corydalis:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - corydalis
    when:
    - condition: flag(library-only)
      buildable: false
  scanner:
    main: scanner.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - corydalis
    when:
    - condition: flag(library-only)
      buildable: false
  db-util:
    main: db-util.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - corydalis
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - corydalis
    - hspec >=2.0.0
    - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
