name:    corydalis
version: "0.4.0"
license: AGPL-3
license-file: LICENCE
category: Image
author:
  - Iustin Pop <iustin@k1024.org>
maintainer:
  - Iustin Pop <iustin@k1024.org>
copyright:
  - (c) 2013 Iustin Pop
github: iustin/corydalis
stability: experimental
synopsis: A photo library management and viewer
description: >
  Corydalis is a simple application to help manage offline (as in
  non-cloud) collections of RAW and processed pictures. It doesn't
  replace your RAW processor but instead acts as a companion to it,
  giving a parallel view on all your files.

  It is also an image viewer, designed to work across and understand
  your entire photo collection; the desktop-only viewers (e.g. Geeqie)
  are folder-based, not collection-based. This aspect aims to offer a
  similar experience of viewing your photos as it would be if you
  stored them in the cloud (but many features are still missing).

  See README.md for more details.

extra-source-files:
  - templates/*
  - static/*/css/*
  - static/*/js/*
  - static/*/webfonts/*
  - README.md
  - docs/*.md
  - stack.yaml
  - package.yaml
  - mkdocs.yml
  - config/favicon.ico
  - config/models
  - config/robots.txt
  - config/routes
  - config/settings.yml.sample
  - config/test-settings.yml
  - app/devel.hs
  - .ghci
  - .dir-locals.el
  - Makefile
  - git-version

dependencies:
  # Due to a bug in GHC 8.0.1, we block its usage
  # See: https://ghc.haskell.org/trac/ghc/ticket/12130
  - base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

  - classy-prelude-yesod
  - aeson
  - async
  - blaze-markup
  - blaze-svg
  - bytestring
  - case-insensitive
  - classy-prelude
  - classy-prelude-conduit
  - clock
  - conduit
  - containers
  - cookie
  - data-default
  - deepseq
  - directory
  - esqueleto
  - fast-logger
  - file-embed
  - filepath
  - foreign-store
  - formatting
  - hjsmin
  - http-conduit
  - lrucaching
  - monad-logger
  - old-locale
  - optparse-applicative
  - persistent
  - persistent-sqlite
  - persistent-template
  - prefix-units
  - random
  - regex-tdfa
  - safe
  - scientific
  - shakespeare
  - store
  - stm
  - template-haskell
  - temporary
  - text
  - time
  - transformers
  - typed-process
  - unix
  - unliftio
  - unordered-containers
  - vector
  - wai
  - wai-extra
  - wai-logger
  - warp
  - warp-tls
  - yaml
  - yesod
  - yesod-auth
  - yesod-auth-hashdb
  - yesod-core
  - yesod-form
  - yesod-static

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs:
    - src
    - app
  exposed-modules:
    - Application
    - Cache
    - Exif
    - Foundation
    - Handler.Browse
    - Handler.Camera
    - Handler.Common
    - Handler.Cookies
    - Handler.Curate
    - Handler.FlaggedImages
    - Handler.Folder
    - Handler.Home
    - Handler.Image
    - Handler.Items
    - Handler.Lens
    - Handler.List
    - Handler.Reload
    - Handler.Search
    - Handler.Settings
    - Handler.Status
    - Handler.Utils
    - Handler.View
    - Handler.Widgets
    - Import
    - Import.NoFoundation
    - Indexer
    - Model
    - Pics
    - Settings
    - Settings.Development
    - Settings.StaticFiles
    - Types
  other-modules:
    - Compat.Orphans

  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -Werror
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -Werror
      - -fwarn-tabs
      - -O2
  - condition: flag(public-site)
    cpp-options: -DPUBLIC_SITE

# Runnable executable for our application
executables:
  corydalis:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - corydalis
    when:
    - condition: flag(library-only)
      buildable: false
  scanner:
    main: scanner.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - corydalis
    when:
    - condition: flag(library-only)
      buildable: false
  db-util:
    main: db-util.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - corydalis
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  test:
    main: Main.hs
    source-dirs: test
    dependencies:
    - corydalis
    - clientsession
    - hspec >=2.0.0
    - hspec-expectations-lifted
    - http-types
    - yesod-test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -qg"'

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
  public-site:
    description: Do not require authentication for most normal handlers.
    manual: true
    default: false
