# Static files are found in this directory
static-dir:     "_env:STATIC_DIR:static"
# Assets (upstream static files) are found in this directory
assets-dir:     "_env:ASSETS_DIR:assets"
# Listen address:
host:           "_env:HOST:*4" # any IPv4 host
# Listen port:
port:           "_env:PORT:3000"
# Canonical URL:
approot:        "_env:APPROOT:http://localhost:3000"
# Useful when running behind a reverse proxy:
ip-from-header: "_env:IP_FROM_HEADER:false"
# Custom message to show on login page
login-msg:      "Hello user!"
https:          false
secure-sessions: false

database:
  # NOTE: By design, this setting prevents the SQLITE_DATABASE environment variable
  # from affecting test runs, so that we don't accidentally affect the
  # production database during testing. If you're not concerned about that and
  # would like to have environment variable overrides, you could instead use
  # something like:
  #
  database: ":memory:"
  poolsize: 1

auth-dummy-login: true

detailed-logging: true
should-log-all: false

config:
  sourcedirs: []
  outputdirs: []
  blacklisteddirs: [".thumbnails"]
  cachedir: "/pics/cache"
  thumbnailsize: 64
  browsingsize: 1024
  autoimgsizes: [1920, 2560]
  demandimgsizes: [3840, 7680, 1920]
  pagesize: 16
  rawexts: ["nef", "raf", "orf", "crw", "tif", "tiff", "dng"]
  jpegexts: ["jpg", "jpeg"]
  sidecarexts: ["xmp"]
  otherexts: ["png"]
  movieexts: ["mov", "avi", "mp4"]
  dirregex: "([0-9]{4}-[0-9]{2}-[0-9]{2})(.*)"
  rangeregex: "(.*_)([0-9]+)-([0-9]+)"
  copyregex: "(.*)(-([0-9]|Edit))"
  peopleprefix: "_People"
  locationprefix: "_Regions"
  ignoreprefix: "_"
